#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

obj-y += us717_mc_ili9881c_bh40ta10103_boe_wxga_101.o




