#
# Makefile for misc devices that really don't fit anywhere else.
#

obj-y += uf281_lcm_gpio_dts.o uf281_tc358775_ltl106hl01.o uf281_tc358775_ltl106hl01_i2c.o

ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc

